### ISSUE TITLE
Icon and text colours for menu items

### ISSUE THREAD

**Issue by SillyPilleus** [spech66/bootstrap-bp-hugo-startpage#2]
How do you change these? I can't work it out! many thanks!

**Comment by spech66** [comment]
You can find the links at `data\links.yml`. There are the blocks for every data entry:

```
    - title: SPech.de Blog
      url: https://www.spech.de
      icon: fas fa-blog
```

You can replace the icon with the codes from https://fontawesome.com/icons?d=gallery&m=free

**Comment by SillyPilleus** [comment]
Sure, but how do you change the default colours? I'm not a fan of the blue...

**Comment by spech66** [comment]
Two ways:

Changing the icon and text color in `main.css` in `assets/css` like:

```
.fa, .far, .fas {
color: #123456;
}
.fa, .far, .fab {
color: #123456;
}
a {
color: #123456;
}
```

Or replace the Bootstrap file with a generated version from https://themestr.app/theme

**Comment by SillyPilleus** [comment]
Awesome, that was really straightforward! Thanks!
