### ISSUE TITLE
Formatting for mobile browsers

### ISSUE THREAD

**Issue by SillyPilleus** [spech66/bootstrap-bp-hugo-startpage#3]
Sorry to keep opening issues, is it possible to format this theme for mobile? I find the top of the menu boxes and the site title are cut off...Would be great if this was possible.

Thanks!

**Comment by spech66** [comment]
Thank you for reporting this bug. I fixed this in the latest commit. Please check it :-)

**Comment by SillyPilleus** [comment]
That has fixed the rendering of the boxes great, but I have nine of them and when viewed in a mobile browser (eg. on an iphone) the top of the page with the title is cut off along with two of the boxes being not visible at all.

Thanks for the support, it's appreciated. I really like the theme and want to adapt it to be a frontpage to my other web services for the less technically inclined in my house to be able to access them from a fixed address. The theme is beautiful and, bar not displaying at the moment on mobile browsers, is a great solution to my problem!

**Comment by spech66** [comment]
Sorry I don't get the new problem. I thought the latest version fixed that and on my mobile it's working. Could you please provide a screenshot?
