### ISSUE TITLE
Linking to about and posts

### ISSUE THREAD

**Issue by jarrodscott** [spech66/bootstrap-bp-hugo-startpage#5]
Hi, 
I really like this theme. I realize that this is a single page template but the `exampleSite` comes with `post/` and an `about.md`. Is it possible to link to these as you would on the homepage to an external site? I have tried different variations in the `links.yml` file . I really just want one link to an about page. Any thoughts? Or am I totally missing something :)

**Comment by spech66** [comment]
Yes the page is at `/about/`. But I think there is no theme layout to render the page.
