### ISSUE TITLE
Is there a way to have two rows of list ?

### ISSUE THREAD

**Issue by hugoio24** [spech66/bootstrap-bp-hugo-startpage#6]
Hi,
Nice theme 👍 
Is there a way to have two (or more) rows of links columns ?

Thanks

**Comment by spech66** [comment]
You could add another link structure in the config and extend the code in the [index.html](https://github.com/spech66/bootstrap-bp-hugo-startpage/blob/master/layouts/index.html). The `{{ range .Site.Data.links }}` part iterates the links.

**Comment by hugoio24** [comment]
Thanks, I'm gonna try that.
