### ISSUE TITLE
change font-family

### ISSUE THREAD

**Issue by oude-gao** [spech66/bootstrap-bp-hugo-startpage#9]
Hi, love the template, thanks for making it available! Just a quick question, I was trying to import google fonts to main.css so I can edit the font-family for the page, but seems like it's not responding. Any suggestion on how to make font changes? Thanks!

**Comment by spech66** [comment]
Hi, thank you for using the theme. To include google fonts you can specify those in your config file like this:

```
[params]
  csscdn=["https://fonts.googleapis.com/css?family=Roboto&display=swap"]
```

or
```
---
csscdn:
    - https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900
---
```

**Comment by oude-gao** [comment]
Thanks, works perfectly!
